### ISSUE TITLE
Design uppbyggnad

### ISSUE THREAD

**Issue by Larsnihlmark** [Larsnihlmark/dota-chat-socket.io#9]
https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto/gigs/119040764/original/baec80edbfa145fd1f38bee739f50b571c7a0b09/design-your-discord-server.png

**Comment by alcr33k** [comment]
Ide på komponent-struktur:
App
	Siderbar
	Rooms
	Main
		Chat
			(SingleMessage)
		ChatInput
